import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SystemContextProvider } from "./context/systemContext";
import MadeBy from "./components/organisms/MadeBy";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GB Contabilidade | Assessoria Contábil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SystemContextProvider>
      <html lang="en">
        <body className={`${inter.className} dark`}>{children}</body>
      </html>
    </SystemContextProvider>
  );
}
